---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
  merge_group:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  ci:
    name: ${{matrix.os}} / OTP-${{matrix.otp-version}}

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        otp-version: [24, 25, 26, 27]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        id: setup-beam
        with:
          otp-version: ${{matrix.otp-version}}
          rebar3-version: 3.23.0

      - name: Test
        run: |
          rebar3 ct
